//random value generated by computer between 1 and 20.
var number = 2; //Math.floor(Math.random() * 20 + 1);

//number guessed by user 
var guesses = document.getElementById("guess");

//value for div 
var result = document.getElementById("result");

document.getElementById("result")
function submitGuess(){
   //using .value like in the other applications were going to pull the user inputted information
   //and compare it to the hard coded value that we have above.
 if (guesses.value == number){
    result.innerHTML = "You've Guessed the Right Answer.";
 } else if (guesses.value > number){
    result.innerHTML = "Your guess was too high.";
 } else {
     result.innerHTML = "Your guess was too low";
 }
}